platform :ios,'8.0'
pod 'AFNetworking','~>2.3.1'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'RongCloudIMKit','2.4.0'
pod 'MBProgressHUD', '~> 0.9.2'
use_frameworks!
pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
pod 'MJRefresh'